<?php

namespace app\modules\pembayaran\models;

use Yii;

/**
 * This is the model class for table "h2h".
 *
 * @property int $id
 * @property string $idTagihan
 * @property int $noRm
 * @property float $totalTagihan
 * @property float|null $bayar
 * @property string $status 1:new;2:lunas;3:batal
 * @property string $publish 1:publish;2:unPub
 * @property string|null $createBy
 * @property string|null $createDate
 * @property string|null $updateBy
 * @property string|null $updateDate
 */
class H2h extends \yii\db\ActiveRecord
{
    public $umum;
    public $naikKelas;
    public $ambulan;
    public $ipj;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'h2h';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_pembayaran');
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['idTagihan', 'noRm'], 'required'],
            [['noRm'], 'integer'],
            [['totalTagihan', 'bayar', 'umum', 'naikKelas', 'ambulan', 'ipj'], 'number'],
            [['createDate', 'updateDate'], 'safe'],
            [['idTagihan'], 'string', 'max' => 10],
            [['status', 'publish'], 'string', 'max' => 1],
            [['createBy', 'updateBy'], 'string', 'max' => 30],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'idTagihan' => 'Id Tagihan',
            'noRm' => 'No Rm',
            'totalTagihan' => 'Total Tagihan',
            'bayar' => 'Bayar',
            'status' => 'Status',
            'publish' => 'Publish',
            'createBy' => 'Create By',
            'createDate' => 'Create Date',
            'updateBy' => 'Update By',
            'updateDate' => 'Update Date',
        ];
    }

    public static function getStatus($id=null){
        $list = [
            1 => 'Blm Lunas',
            2 => 'Lunas',
        ];
        if($id == null){
            return $list;
        }
        return $list[$id];
    }

    public function beforeSave($insert)
    {
        parent::beforeSave($insert); // TODO: Change the autogenerated stub
        if($insert){
            $this->createBy = Yii::$app->user->identity->username;
            $this->createDate = date('Y-m-d H:i:s');
        }
        else{
            $this->updateBy = Yii::$app->user->identity->username;
            $this->updateDate = date('Y-m-d H:i:s');
        }
        return true;
    }
}
