<?php

namespace app\modules\pembayaran\models;

use Yii;

/**
 * This is the model class for table "jenis_ambulan".
 *
 * @property int $id
 * @property string $deskripsi
 * @property int $jsProp
 * @property int $jpProp
 * @property float $hargaPerKM
 * @property string $publish
 * @property string|null $createDate
 * @property string|null $createBy
 * @property string|null $updateDate
 * @property string|null $updateBy
 *
 * @property TagihanAmbulan[] $tagihanAmbulans
 */
class JenisAmbulan extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'jenis_ambulan';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_pembayaran');
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['deskripsi', 'jsProp', 'jpProp', 'hargaPerKM'], 'required'],
            [['jsProp', 'jpProp'], 'integer'],
            [['hargaPerKM'], 'number'],
            [['createDate', 'updateDate'], 'safe'],
            [['deskripsi'], 'string', 'max' => 35],
            [['publish'], 'string', 'max' => 1],
            [['createBy', 'updateBy'], 'string', 'max' => 30],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'deskripsi' => 'Deskripsi',
            'jsProp' => 'Js Prop',
            'jpProp' => 'Jp Prop',
            'hargaPerKM' => 'Harga Per Km',
            'publish' => 'Publish',
            'createDate' => 'Create Date',
            'createBy' => 'Create By',
            'updateDate' => 'Update Date',
            'updateBy' => 'Update By',
        ];
    }

    public static function getPublish($id=null){
        $list = [
            1 => 'Ya',
            2 => 'Tidak',
        ];
        if($id == null){
            return $list;
        }
        return $list[$id];
    }

    /**
     * Gets query for [[TagihanAmbulans]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getTagihanAmbulans()
    {
        return $this->hasMany(TagihanAmbulan::class, ['idJenisAmbulan' => 'id']);
    }

    public function beforeSave($insert)
    {
        parent::beforeSave($insert); // TODO: Change the autogenerated stub
        if($insert){
            $this->createBy = Yii::$app->user->identity->username;
            $this->createDate = date('Y-m-d H:i:s');
        }
        else{
            $this->updateBy = Yii::$app->user->identity->username;
            $this->updateDate = date('Y-m-d H:i:s');
        }
        return true;
    }
}
