<?php

namespace app\modules\jaspel\models;

use Yii;

/**
 * This is the model class for table "jaspel".
 *
 * @property int $id
 * @property int $bulan
 * @property int $tahun
 * @property string $idReg
 * @property string $tgl
 * @property int $noRm
 * @property string $namaPasien
 * @property string $idTagihan
 * @property int $idCaraBayar
 * @property string $caraBayar
 * @property float $tagihanRs
 * @property float $klaim
 * @property float $jpRs
 * @property float $jpFix
 * @property int|null $publish 1:publish;2:unpublish
 * @property string|null $createBy
 * @property string|null $createDate
 * @property string|null $updateBy
 * @property string|null $updateDate
 *
 * @property JaspelTemp[] $jaspelTemps
 */
class Jaspel extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'jaspel';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_jaspel');
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['bulan', 'tahun', 'idReg', 'tgl', 'noRm', 'namaPasien', 'idTagihan', 'idCaraBayar', 'caraBayar', 'tagihanRs', 'klaim', 'jpRs', 'jpFix'], 'required'],
            [['bulan', 'tahun', 'noRm', 'idCaraBayar', 'publish'], 'integer'],
            [['tgl', 'createDate', 'updateDate'], 'safe'],
            [['tagihanRs', 'klaim', 'jpRs', 'jpFix'], 'number'],
            [['idReg', 'idTagihan'], 'string', 'max' => 10],
            [['namaPasien'], 'string', 'max' => 100],
            [['caraBayar'], 'string', 'max' => 21],
            [['createBy', 'updateBy'], 'string', 'max' => 15],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'bulan' => 'Bulan',
            'tahun' => 'Tahun',
            'idReg' => 'Id Reg',
            'tgl' => 'Tgl',
            'noRm' => 'No Rm',
            'namaPasien' => 'Nama Pasien',
            'idTagihan' => 'Id Tagihan',
            'idCaraBayar' => 'Id Cara Bayar',
            'caraBayar' => 'Cara Bayar',
            'tagihanRs' => 'Tagihan Rs',
            'klaim' => 'Klaim',
            'jpRs' => 'Jp Rs',
            'jpFix' => 'Jp Fix',
            'publish' => 'Publish',
            'createBy' => 'Create By',
            'createDate' => 'Create Date',
            'updateBy' => 'Update By',
            'updateDate' => 'Update Date',
        ];
    }

    /**
     * Gets query for [[JaspelTemps]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getJaspelTemps()
    {
        return $this->hasMany(JaspelTemp::class, ['idJaspel' => 'id']);
    }

    public static function getPublish($id=null){
        $list = [
            1 => 'Publish',
            2 => 'UnPublish',
        ];
        if($id == null){
            return $list;
        }
        return $list[$id];
    }

    public static function getBulan($id=null){
        $list = [
            1 => 'Januari',
            2 => 'Februari',
            3 => 'Maret',
            4 => 'April',
            5 => 'Mei',
            6 => 'Juni',
            7 => 'Juli',
            8 => 'Agustus',
            9 => 'September',
            10 => 'Oktober',
            11 => 'November',
            12 => 'Desember',
        ];
        if($id == null){
            return $list;
        }
        return $list[$id];
    }

    public static function getTahun($id=null){
        $list = [
            2024 => '2024',
            //2025 => '2025',
        ];
        if($id == null){
            return $list;
        }
        return $list[$id];
    }

    public function beforeSave($insert)
    {
        parent::beforeSave($insert); // TODO: Change the autogenerated stub
        if($insert){
            $this->createBy = Yii::$app->user->identity->username;
            $this->createDate = date('Y-m-d H:i:s');
        }
        else{
            $this->updateBy = Yii::$app->user->identity->username;
            $this->updateDate = date('Y-m-d H:i:s');
        }
        return true;
    }
}
