<?php

namespace app\modules\jaspel\models;

use Yii;

/**
 * This is the model class for table "kronis".
 *
 * @property int $id
 * @property string $idReg
 * @property string $noSep
 * @property float $tarifKronis
 * @property float|null $klaimKronis
 * @property int|null $publish 1: publish; 2:unpublish
 * @property string|null $createBy
 * @property string|null $createDate
 * @property string|null $updateBy
 * @property string|null $updateDate
 */
class Kronis extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'kronis';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_jaspel');
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['idReg', 'noSep'], 'required'],
            [['tarifKronis', 'klaimKronis'], 'number'],
            [['publish'], 'integer'],
            [['createDate', 'updateDate'], 'safe'],
            [['idReg'], 'string', 'max' => 10],
            [['noSep'], 'string', 'max' => 19],
            [['createBy', 'updateBy'], 'string', 'max' => 30],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'idReg' => 'Id Reg',
            'noSep' => 'No Sep',
            'tarifKronis' => 'Tarif Kronis',
            'klaimKronis' => 'Klaim Kronis',
            'publish' => 'Publish',
            'createBy' => 'Create By',
            'createDate' => 'Create Date',
            'updateBy' => 'Update By',
            'updateDate' => 'Update Date',
        ];
    }

    public function beforeSave($insert)
    {
        parent::beforeSave($insert); // TODO: Change the autogenerated stub
        if($insert){
            $this->createBy = Yii::$app->user->identity->username;
            $this->createDate = date('Y-m-d H:i:s');
        }
        else{
            $this->updateBy = Yii::$app->user->identity->username;
            $this->updateDate = date('Y-m-d H:i:s');
        }
        return true;
    }
}
